# This workflow will do a clean install of node dependencies, build the source     code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on: 
  pull_request:
    types: [labeled]

env:
  AZURE_WEBAPP_NAME: ghlab-staging




jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'staging')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy app to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ghlab-staging
          publish-profile: ${{ secrets.PUBLISH }}
